// Typst-native book — NOT generated by docs/md2pdf.py (there is no Markdown source).
// Build:
//   typst compile --root . docs/training-guide/main.typ \
//     docs/training-guide/AI-Datacenter-Network-Training-Guide.pdf

#import "lib.typ": *

#set document(
  title: "The AI Datacenter Network: A Training Guide for Senior Enterprise Network Engineers",
  author: "Prepared for interview readiness — Senior AI Datacenter Network Engineer",
)

#set page(
  paper: "us-letter",
  margin: (x: 1in, y: 0.9in),
  numbering: "1",
  header: context {
    if counter(page).get().first() > 1 [
      #text(size: 8pt, fill: gray)[The AI Datacenter Network — Training Guide]
      #h(1fr)
      #text(size: 8pt, fill: gray)[Senior AI Network Engineer Interview Preparation]
    ]
  },
)

#set text(size: 10pt)
#set par(justify: true, leading: 0.62em)
#set heading(numbering: "1.1")
#show heading.where(level: 1): it => {
  pagebreak(weak: true)
  block(above: 1.2em, below: 0.9em)[
    #text(size: 19pt, fill: accent, weight: "bold")[#it]
  ]
}
#show heading.where(level: 2): it => block(above: 1.1em, below: 0.6em)[
  #text(size: 13pt, fill: accent.darken(10%))[#it]
]
#show heading.where(level: 3): it => block(above: 1em, below: 0.5em)[
  #text(size: 11pt)[#it]
]
#show raw.where(block: true): it => block(
  fill: rgb("#f6f8fa"),
  inset: 8pt,
  radius: 3pt,
  width: 100%,
  text(size: 8.5pt, it),
)
#show raw.where(block: false): it => box(
  fill: rgb("#f2f3f4"),
  inset: (x: 3pt, y: 0pt),
  outset: (y: 3pt),
  radius: 2pt,
  text(size: 9pt, it),
)
#set table(stroke: 0.5pt + rgb("#b0b8bf"), inset: 6pt)
#show table: set text(size: 9pt)

// ── Title page ──────────────────────────────────────────────
#page(numbering: none, header: none)[
  #v(1.6in)
  #align(center)[
    #text(size: 26pt, weight: "bold", fill: accent)[The AI Datacenter Network]
    #v(0.3em)
    #text(size: 15pt, fill: accent.darken(20%))[From Enterprise Networking to Distributed GPU Fabrics]
    #v(2.2em)
    #line(length: 55%, stroke: 1pt + accent)
    #v(2.2em)
    #text(size: 12pt)[
      A comprehensive training guide for senior enterprise and service-provider \
      network engineers preparing for a *Senior AI Datacenter Network Engineer* role.
    ]
    #v(1.4em)
    #text(size: 10.5pt, style: "italic")[
      Purpose: build the depth needed to speak intelligently with hiring managers \
      and technical teams about RDMA fabrics, lossless Ethernet, GPU collective \
      traffic, 400G/800G physical plant, host networking, and fabric operations.
    ]
    #v(3.4em)
    #text(size: 10pt, fill: gray)[July 2026 · Prepared with source material on AI fabric skill gaps]
  ]
]

// ── Table of contents ───────────────────────────────────────
#page(header: none)[
  #text(size: 17pt, weight: "bold", fill: accent)[Contents]
  #v(1em)
  #outline(title: none, depth: 2)
]

#include "ch01-mental-model.typ"
#include "ch02-transport.typ"
#include "ch03-lossless.typ"
#include "ch04-workloads.typ"
#include "ch05-topology.typ"
#include "ch06-physical.typ"
#include "ch07-host.typ"
#include "ch08-observability.typ"
#include "ch09-orchestration.typ"
#include "ch10-facilities-dci.typ"
#include "ch11-interview.typ"
#include "ch12-learning-path.typ"
